# Generated by Django 3.0.6 on 2020-05-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='label',
            field=models.CharField(choices=[('ficcion', 'FICCION'), ('ciencia', 'CIENCIA')], default='ficcion', max_length=7),
        ),
    ]
