# Generated by Django 3.0.6 on 2020-05-12 17:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('my_blog', '0002_post_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='label',
            field=models.CharField(choices=[('ficción', 'ficción'), ('ciencia', 'ciencia')], default='ficción', max_length=7),
        ),
    ]
