# Generated by Django 3.0.6 on 2020-05-21 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0005_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
    ]
