# Generated by Django 3.0.6 on 2020-05-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0006_auto_20200521_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='label',
            field=models.CharField(choices=[('Ficción', 'Ficción'), ('Ciencia', 'Ciencia')], default='Ficción', max_length=7),
        ),
    ]
